include::header.adoc[]

:title: Lab 2: Variables, Converting Data Types, Input / Output
:Author Initials: KRS
:Date:    2026-08-27
:Revision: 0.1

[discrete]
= {title}

[discrete]
= Objectives

1. The main goals for this lab are:
2. Variables: defining and assigning
3. Data types: String, double, int
4. System.out.println(), System.out.print()
5. System.console().readLine() for reading in data
6. arithmetic operators: +, *, -, \, %
7. String concatenation with +
8. Operators and expressions, order of operations


Make sure to write down your answers for each **Question** below. Whenever you see **TODO**, 
that means there is an action item for you to complete. When you see **Question**, that
means you should fill in your answer on the worksheet provided to you.
When you believe you have finished the lab, show Prof. Shiptoski your work.

// [source, subs="quotes"]
// ----
// $ **./make hello**
// gcc -g -Wno-unused-variable -Wno-unused-but-set-variable   -Wl,-rpath=. hello.c -o hello 
// $ **./hello**
// Hello World
// ----
---
[discrete]
= 0. CS Lab Machine Directory Setup

In the first lab, you should have set up your `/lab01` directory.

On your lab machine, open the terminal, and run the following commands.

[source, subs="quotes"]
----
cd /home/your-username/cs113/labs/lab01
pwd
----

You should see this after running `pwd`: `/home/your-username/cs113/labs/01`

Great, we have verified you have a `/lab01` directory, and set your current working
directory to your `/lab01` directory.


---
[discrete]
= 1. Expressions

For each expression, write down the **value** of the expression, and the **date type**
of the expression.

**1:** 2 + 3

**Answer:** ______

**2:** 2.0 + 3

**Answer:** ______

**3:** 5.5 / 10

**Answer:** ______

**4:** 5 - 2 * 3

**Answer:** ______

**5:** "123"

**Answer:** ______

**6:** 48 % 2

**Answer:** ______

**7:** 55 % 4

**Answer:** ______

**8:** 2 + 4 * 2 + 1

**Answer:** ______

**8:** "i" + "love" + "CS113!"

**Answer:** ______

---
[discrete]
= 3. Downloading & Viewing Files

For the rest of this lab, you should be working in the `labs/lab1/` directory.

[discrete]
==== `wget` command

We are now going to start looking at some data. `wget` is a “non-interactive network downloader,” in
other words it is a command that will download files from the internet.

**TODO:** Run `wget` and follow the instructions to figure out how it works.

**Question 20:** What argument does `wget` require?

**Answer:** ______

We are going to download a book from link:https://www.gutenberg.org/[Project Gutenberg], an awesome 
project that is dedicated to the creation and distribution of eBooks.

**TODO:** On Project Gutenberg, search for a book that you are interested in. Then use `wget` to 
download the book. 

**Note:** Make sure to download the plaintext version. This can be found by clicking on 
**Other formats & older devices**. Right click on **Plain Text** and click copy link.

**Example Command:**

[source, subs="quotes"]
----
wget https://www.gutenberg.org/ebooks/345.txt.utf-8
----

**Question 21:** What command can you use to determine that the file has downloaded? (Write your
answer here, and then actually run the command to ensure it is there).

**Answer:** ______

---

[discrete]
==== `mv` command

`mv` is a command that can be used to move from one directory to another, or even rename files.

**Question 22:** Use `mv` to rename the file to be the name of the book. Make sure to not have 
any spaces in the name of the file and that the file name ends in .txt. Write down the command
you used here.

**Answer:** ______

---

[discrete]
==== `cat` command

The last command we’ll use in this lab, is `cat`. We are going to figure out what `cat` 
does by playing with it.

**Question 23:** Run `cat`. Next, type a message into the command line and press `Enter`. What happened?

**Answer:** ______

Once you are finished with `cat`, hit `CTRl-C`, this will terminate the `cat` program.

**TODO:** Using the same way we figured out how to use other commands, use the same method to read more about `cat`.

**TODO:** Then, use `cat` to print out the entire book.

**TODO:** Read the entire book. Just kidding! This is the end of the first lab, please give your
completed worksheet to Professor Shiptoski.
