include::header.adoc[]

:title: CS223: Systems Programming - Quiz 1 (Spring 2026)
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1

[discrete]
= {title}



Name: 
{nbsp} +
{nbsp} +
{nbsp} +

Complete the following exercises in 50 minutes. This quiz is closed book with the 
exception of one cheat sheet.

++++
<div class="pagebreak"> </div>
++++

[discrete]
= Question 1

Consider the following sequence of commands. On each line, list what each command 
does. If the command produces output, list what the output would be. Assume that 
the first command runs in the directory `/home/zu`

[cols="1,3"]
|===
|Command |Description
| mkdir A|
| cd A|
| echo "hello" > A.txt|
| cat A.txt|
| ls|
| mkdir B|
| mkdir C|
| cd B|
| ls ..|
|=== 

In the space below, draw the file hierarchy under the directory `/home/zu. 

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

What is the current working directory after running the above commands?

{nbsp} +
{nbsp} +

What is the absolute path to the file `A.txt`?

{nbsp} +
{nbsp} +

What is the relative path to the file `A.txt` from the home directory, `/home/zu`?

++++
<div class="pagebreak"> </div>
++++

[discrete]
= Question 2

Give the sizes in bytes for the following variables based on their
declarations. Make sure to give a rationale for your answer. 
Assume standard sizes for basic data types (on a 64 bit
system), such as those in your book, _Dive into Systems_. If the variable is 
a pointer give the size of the data it points to.

[source]
----
struct mystery {
  int flag;
  char message[4];
  int* status;
  struct mystery* next;
};
----

[cols="1,1"]
|===
|Variable
|Size and Rationale

| `float a = 8.5;`
|

| `&a`
|

| `const char* code = "-3";`
|

| `struct mystery* m = malloc(sizeof(struct mystery) * 3);`
|

| `m->next`
|

| `m.flag`
|

| `m.message[3]`
|

| `m.message`
|

| `*(m->status)`
|

|===

++++
<div class="pagebreak"> </div>
++++

[discrete]
= Question 3

A) Draw the function stack at the line indicated by the comment in `foo`.
Please include intermediate values in your diagram, including the variable `i`.

B) What is the output of this program? E.g. what is printed?

[source]
----
#include <stdio.h>
#include <string.h>

char* foo(char* str, char c)
{
  int n = strlen(str);
  for(int i = 0; i < n; i++)
  {
    if (str[i] == c)
    {
      str[i] = '\0';
      return str;
    }
  }
  return NULL;
}
 
int main()
{
  char buffer[8];
  strcpy(buffer, "a,b,c");

  char* s = foo(buffer, ',');
  printf("%s\n", s);
}
----

++++
<div class="pagebreak"> </div>
++++

[discrete]
= Question 4

Consider the following program. 

* Suppose we would like to create a 5 by 2 array using an array or arrays method. Show how we can fill in the code below to create a 2D array with the right size. 
* How much memory is allocated on the heap to create the array?
* Draw the stack diagram on the line indicated by the comment.
* In the space below this program, write code to initialize the same 5x2 array using a flat array.

[source]
----
  5 int main() {                                                                    
  6     int** array = malloc(sizeof(int*) * ____);                                     
  7     assert(array != NULL); // abort program on error                            
  8                                                                                 
  9     int idx = 2;                                                                
 10     for (int i = 0; i < ____; i++) {                                               
 11         array[i] = malloc(sizeof(int) * ___);                                     
 12         for (int j = 0; j < ___; j++) {                                           
 13             array[i][j] = idx;
 14               idx = idx + 2;                                                
 15         }                                                                       
 16     }    
 17     // Draw the stack here!                                                                            
 18           
----

++++
<div class="pagebreak"> </div>
++++


[discrete]
= Question 5

When Cedric runs his program with valgrind, he gets the following error.

[source]
----
==798== Conditional jump or move depends on uninitialised value(s)
==798==    at 0x48DFAD6: __vfprintf_internal (vfprintf-internal.c:1516)
==798==    by 0x48C979E: printf (printf.c:33)
==798==    by 0x1091F0: printValues (cedric-f24.c:6)
==798==    by 0x10924E: main (cedric-f24.c:15)
==798==
==798== Use of uninitialised value of size 8
==798==    at 0x48C32EB: _itoa_word (_itoa.c:177)
==798==    by 0x48DEABD: __vfprintf_internal (vfprintf-internal.c:1516)
==798==    by 0x48C979E: printf (printf.c:33)
==798==    by 0x1091F0: printValues (cedric-f24.c:6)
==798==    by 0x10924E: main (cedric-f24.c:15)
0 0 0 0 0 0 0 0 0 0
==798== Invalid free() / delete / delete[] / realloc()
==798==    at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==798==    by 0x10925A: main (cedric-f24.c:16)
==798==  Address 0x4a95040 is 0 bytes inside a block of size 40 free'd
==798==    at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==798==    by 0x109212: printValues (cedric-f24.c:9)
==798==    by 0x10924E: main (cedric-f24.c:15)
==798==  Block was alloc'd at
==798==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==798==    by 0x109239: main (cedric-f24.c:14)
----

Here is his code.  What do the valgrind errors mean and how can Cedric fix his
program? Write your answer in the space below, next to Cedric's program.

[source]
----
void printValues(int* v, int n) {
  for (int i = 0; i < n; i++) {
    printf("%d ", v[i]);
  }
  printf("\n");
  free(v);
}

int main() {
  int n = 10;
  int *values = malloc(sizeof(int) * n);
  printValues(values, n);
  free(values);
  return 0; 
}
----


++++
<div class="pagebreak"> </div>
++++

[discrete]
= Question 6

Part 1: Draw a stack diagram for the following code.  

[source]
----
  3 struct dataT {                                                                  
  4   int i, b, c;                                                                  
  5 };                                                                              
  6                                                                                 
  7 struct nodeT {                                                                  
  8   struct dataT* first;                                                          
  9   struct dataT* second;                                                         
 10 };                                                                              
 11                                                                                 
 12 int main() {                                                                    
 13                                                                                 
 14   struct dataT data1 = {1, 2, 3};                                               
 15   struct dataT data2 = {-10, -20, -30};                                         
 16   struct nodeT* node = malloc(sizeof(struct nodeT));                            
 17   node->first = &data1;                                                         
 18   node->second = &data2;                                                        
 19                                                                                 
 20   // Draw stack here                                                            
 21   free(node);                                                                   
 22 }  
----

Part 2: Suppose we wish to refactor the above code so that `node` is created and initialized 
using a function called `init`, as shown below. Show how you would define and implement the 
function `init` such that `node` is created in the same way as before.

[source]
----
int main() {                                                                    
                                                                                
  struct dataT data1 = {1, 2, 3};                                               
  struct dataT data2 = {-10, -20, -30};                                         
  struct nodeT* node = init(&data1, &data2);
                                                                                
  free(node);                                                                   
}  
----